Repository Susanghan-guys/be, pull requests merged in 2025-08, with the labels that each got.

#94 fix: 픽셀 검증 삭제
  src/main/java/com/susanghan_guys/server/work/application/validator/DcaWorkValidator.java
  src/main/java/com/susanghan_guys/server/work/dto/request/DcaWorkSubmissionRequest.java
  src/main/java/com/susanghan_guys/server/work/exception/code/WorkErrorCode.java
Labels: 🐛bug, 🚨hotfix

#99 feat: YCC 작품 전체 총평 및 세부 총평 분석
  src/main/java/com/susanghan_guys/server/file/application/PdfFileService.java
  src/main/java/com/susanghan_guys/server/file/domain/PdfFile.java
  src/main/java/com/susanghan_guys/server/file/presentation/FileController.java
  src/main/java/com/susanghan_guys/server/file/presentation/response/FileSuccessCode.java
  src/main/java/com/susanghan_guys/server/file/presentation/swagger/FileSwagger.java
  src/main/java/com/susanghan_guys/server/global/client/openai/adapter/OpenAiAdapter.java
  src/main/java/com/susanghan_guys/server/global/client/openai/prompt/WorkEvaluationPrompt.java
  src/main/java/com/susanghan_guys/server/personalwork/application/WorkSummaryService.java
  src/main/java/com/susanghan_guys/server/personalwork/application/YccWorkEvaluationService.java
  src/main/java/com/susanghan_guys/server/personalwork/application/factory/OpenAiFactory.java
  src/main/java/com/susanghan_guys/server/personalwork/application/port/OpenAiPort.java
  src/main/java/com/susanghan_guys/server/personalwork/application/validator/PersonalWorkValidator.java
  src/main/java/com/susanghan_guys/server/personalwork/domain/type/DetailEvalType.java
  src/main/java/com/susanghan_guys/server/personalwork/domain/type/EvaluationType.java
  src/main/java/com/susanghan_guys/server/personalwork/dto/response/YccDetailEvaluationResponse.java
  src/main/java/com/susanghan_guys/server/personalwork/dto/response/YccWorkEvaluationResponse.java
  src/main/java/com/susanghan_guys/server/personalwork/presentation/WorkSummaryController.java
  src/main/java/com/susanghan_guys/server/personalwork/presentation/YccWorkEvaluationController.java
  src/main/java/com/susanghan_guys/server/personalwork/presentation/response/PersonalWorkSuccessCode.java
  src/main/java/com/susanghan_guys/server/personalwork/presentation/swagger/WorkSummarySwagger.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/persistence/WorkRepository.java
Labels: ✨feature

#108 feat: 내 리포트 공모전 팀원 조회 API 및 리포트 상태 저장
  src/main/java/com/susanghan_guys/server/file/presentation/swagger/FileSwagger.java
  src/main/java/com/susanghan_guys/server/mail/presentation/swagger/MailSwagger.java
  src/main/java/com/susanghan_guys/server/personalwork/application/YccWorkEvaluationService.java
  src/main/java/com/susanghan_guys/server/work/application/ReportService.java
  src/main/java/com/susanghan_guys/server/work/application/validator/ReportValidator.java
  src/main/java/com/susanghan_guys/server/work/domain/Work.java
  src/main/java/com/susanghan_guys/server/work/dto/response/ReportInfoResponse.java
  src/main/java/com/susanghan_guys/server/work/exception/code/WorkErrorCode.java
  src/main/java/com/susanghan_guys/server/work/presentation/ReportController.java
  src/main/java/com/susanghan_guys/server/work/presentation/swagger/ReportSwagger.java
Labels: ✨feature

#111 fix: 리포트 정보 조회 오류
  src/main/java/com/susanghan_guys/server/work/application/validator/ReportValidator.java
Labels: 🐛bug, 🚨hotfix

#114 fix: 리포트 코드 인증 사용자 리포트 조회 버그
  src/main/java/com/susanghan_guys/server/personalwork/application/YccWorkEvaluationService.java
  src/main/java/com/susanghan_guys/server/personalwork/application/validator/PersonalWorkValidator.java
  src/main/java/com/susanghan_guys/server/work/application/validator/ReportValidator.java
  src/main/java/com/susanghan_guys/server/work/dto/response/ReportInfoResponse.java
Labels: 🐛bug

#117 feat: 리포트 공유하기 API
  src/main/java/com/susanghan_guys/server/mail/application/MailService.java
  src/main/java/com/susanghan_guys/server/mail/exception/code/MailErrorCode.java
  src/main/java/com/susanghan_guys/server/work/application/ReportService.java
  src/main/java/com/susanghan_guys/server/work/dto/response/ReportCodeResponse.java
  src/main/java/com/susanghan_guys/server/work/dto/response/ReportSharingResponse.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/persistence/WorkRepository.java
  src/main/java/com/susanghan_guys/server/work/presentation/ReportController.java
  src/main/java/com/susanghan_guys/server/work/presentation/response/WorkSuccessCode.java
  src/main/java/com/susanghan_guys/server/work/presentation/swagger/ReportSwagger.java
Labels: ✨feature

#120 feat: 리포트 코드 인증 API 수정
  src/main/java/com/susanghan_guys/server/work/application/ReportService.java
  src/main/java/com/susanghan_guys/server/work/presentation/ReportController.java
  src/main/java/com/susanghan_guys/server/work/presentation/swagger/ReportSwagger.java
Labels: ✨feature

#127 feat: 리포트 관련 내부용 api 구현
  src/main/java/com/susanghan_guys/server/personalwork/application/DcaBriefEvaluationService.java
  src/main/java/com/susanghan_guys/server/personalwork/application/DcaWorkEvaluationService.java
  src/main/java/com/susanghan_guys/server/personalwork/application/ReportInternalService.java
  src/main/java/com/susanghan_guys/server/personalwork/application/WorkSummaryService.java
  src/main/java/com/susanghan_guys/server/personalwork/application/YccWorkEvaluationService.java
  src/main/java/com/susanghan_guys/server/personalwork/dto/response/ReportPipelineResponse.java
  src/main/java/com/susanghan_guys/server/personalwork/exception/code/PersonalWorkErrorCode.java
  src/main/java/com/susanghan_guys/server/personalwork/presentation/ReportInternalController.java
  src/main/java/com/susanghan_guys/server/personalwork/presentation/response/PersonalWorkSuccessCode.java
  src/main/java/com/susanghan_guys/server/personalwork/presentation/swagger/ReportInternalSwagger.java
Labels: ✨feature

#130 release: 운영 서버에 현재까지의 진행 상황 반영
  src/main/java/com/susanghan_guys/server/mail/application/MailService.java
  src/main/java/com/susanghan_guys/server/work/application/ReportService.java
Labels: 🌏deploy
