Repository Susanghan-guys/be, pull requests merged in 2025-07, with the labels that each got.

#5 chore: coderabbit 설정
  .coderabbit.yaml
  .github/pull-request-template.md
  .gitignore
  src/main/resources/application.properties
Labels: ✨feature, ⚙️setting

#7 chore: Jira 연동
  .github/ISSUE_TEMPLATE/bug-repot-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/issue-template.yml
  .github/ISSUE_TEMPLATE/refactor-template.md
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
Labels: ✨feature, ⚙️setting

#12 fix: Jira 연동 오류 수정
  .github/workflows/create-jira-issue.yml
Labels: 🐛bug

#18 chore: 초기 엔티티 설계
  build.gradle
  src/main/java/com/susanghan_guys/server/ServerApplication.java
  src/main/java/com/susanghan_guys/server/agenda/domain/Agenda.java
  src/main/java/com/susanghan_guys/server/contest/domain/Contest.java
  src/main/java/com/susanghan_guys/server/feedback/domain/Feedback.java
  src/main/java/com/susanghan_guys/server/global/domain/BaseEntity.java
  src/main/java/com/susanghan_guys/server/personalwork/domain/Critic.java
  src/main/java/com/susanghan_guys/server/personalwork/domain/PersonalCritic.java
  src/main/java/com/susanghan_guys/server/personalwork/domain/PersonalWork.java
  src/main/java/com/susanghan_guys/server/personalwork/domain/type/CriticType.java
  src/main/java/com/susanghan_guys/server/personalwork/domain/type/ItemType.java
  src/main/java/com/susanghan_guys/server/user/domain/User.java
  src/main/java/com/susanghan_guys/server/user/domain/type/Channel.java
  src/main/java/com/susanghan_guys/server/user/domain/type/Purpose.java
  src/main/java/com/susanghan_guys/server/user/domain/type/Role.java
  src/main/java/com/susanghan_guys/server/user/domain/type/SocialLogin.java
  src/main/java/com/susanghan_guys/server/work/domain/Work.java
  src/main/java/com/susanghan_guys/server/work/domain/type/Brand.java
  src/main/java/com/susanghan_guys/server/work/domain/type/Category.java
Labels: ✨feature, ⚙️setting

#22 feat: 구글 소셜 로그인 구현
  build.gradle
  src/main/java/com/susanghan_guys/server/global/common/code/ErrorCode.java
  src/main/java/com/susanghan_guys/server/global/config/RedisConfig.java
  src/main/java/com/susanghan_guys/server/global/config/SecurityConfig.java
  src/main/java/com/susanghan_guys/server/global/config/SwaggerConfig.java
  src/main/java/com/susanghan_guys/server/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/susanghan_guys/server/global/jwt/JwtProperties.java
  src/main/java/com/susanghan_guys/server/global/jwt/JwtProvider.java
  src/main/java/com/susanghan_guys/server/global/oauth2/application/CustomOAuth2UserService.java
  src/main/java/com/susanghan_guys/server/global/oauth2/domain/OAuth2UserInfo.java
  src/main/java/com/susanghan_guys/server/global/oauth2/domain/RefreshToken.java
  src/main/java/com/susanghan_guys/server/global/oauth2/dto/request/OAuth2Request.java
  src/main/java/com/susanghan_guys/server/global/oauth2/dto/response/OAuth2Response.java
  src/main/java/com/susanghan_guys/server/global/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/susanghan_guys/server/global/oauth2/infrastructure/mapper/OAuth2Mapper.java
  src/main/java/com/susanghan_guys/server/global/oauth2/infrastructure/persistence/RefreshTokenRepository.java
  src/main/java/com/susanghan_guys/server/global/oauth2/infrastructure/userinfo/GoogleUserInfo.java
  src/main/java/com/susanghan_guys/server/global/security/CustomUserDetailService.java
  src/main/java/com/susanghan_guys/server/global/security/CustomUserDetails.java
  src/main/java/com/susanghan_guys/server/global/security/SecurityUtils.java
  src/main/java/com/susanghan_guys/server/user/domain/User.java
  src/main/java/com/susanghan_guys/server/user/infrastructure/UserRepository.java
  src/main/java/com/susanghan_guys/server/user/infrastructure/mapper/UserMapper.java
Labels: ✨feature

#27 feat: 로그아웃 및 refreshToken 재발급
  src/main/java/com/susanghan_guys/server/global/common/code/ErrorCode.java
  src/main/java/com/susanghan_guys/server/global/common/code/SuccessCode.java
  src/main/java/com/susanghan_guys/server/global/config/RedisConfig.java
  src/main/java/com/susanghan_guys/server/global/config/SecurityConfig.java
  src/main/java/com/susanghan_guys/server/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/susanghan_guys/server/global/jwt/JwtProvider.java
  src/main/java/com/susanghan_guys/server/global/oauth2/application/CustomOAuth2UserService.java
  src/main/java/com/susanghan_guys/server/global/oauth2/application/TokenBlackListService.java
  src/main/java/com/susanghan_guys/server/global/oauth2/dto/request/OAuth2Request.java
  src/main/java/com/susanghan_guys/server/global/oauth2/dto/response/OAuth2Response.java
  src/main/java/com/susanghan_guys/server/global/oauth2/infrastructure/mapper/OAuth2Mapper.java
  src/main/java/com/susanghan_guys/server/global/oauth2/infrastructure/persistence/RefreshTokenRepository.java
  src/main/java/com/susanghan_guys/server/global/security/CustomUserDetailService.java
  src/main/java/com/susanghan_guys/server/user/application/UserAuthService.java
  src/main/java/com/susanghan_guys/server/user/dto/request/RefreshTokenRequest.java
  src/main/java/com/susanghan_guys/server/user/dto/response/RefreshTokenResponse.java
  src/main/java/com/susanghan_guys/server/user/infrastructure/persistence/UserRepository.java
  src/main/java/com/susanghan_guys/server/user/presentation/UserAuthController.java
  src/main/java/com/susanghan_guys/server/user/presentation/swagger/UserAuthSwagger.java
Labels: ✨feature

#34 feat: 온보딩 관련 API 구현
  .gitignore
  src/main/java/com/susanghan_guys/server/global/common/code/ErrorCode.java
  src/main/java/com/susanghan_guys/server/global/common/code/SuccessCode.java
  src/main/java/com/susanghan_guys/server/global/config/SwaggerConfig.java
  src/main/java/com/susanghan_guys/server/global/security/CurrentUserProvider.java
  src/main/java/com/susanghan_guys/server/global/security/CustomUserDetails.java
  src/main/java/com/susanghan_guys/server/user/application/UserService.java
  src/main/java/com/susanghan_guys/server/user/domain/User.java
  src/main/java/com/susanghan_guys/server/user/domain/type/Channel.java
  src/main/java/com/susanghan_guys/server/user/domain/type/Purpose.java
  src/main/java/com/susanghan_guys/server/user/domain/type/Role.java
  src/main/java/com/susanghan_guys/server/user/dto/request/UserOnboardingRequest.java
  src/main/java/com/susanghan_guys/server/user/dto/request/UserTermsRequest.java
  src/main/java/com/susanghan_guys/server/user/presentation/UserController.java
  src/main/java/com/susanghan_guys/server/user/presentation/swagger/UserSwagger.java
Labels: ✨feature

#37 fix: 소셜 로그인 프론트 주소로 리다이렉트
  src/main/java/com/susanghan_guys/server/global/oauth2/handler/OAuth2SuccessHandler.java
Labels: 🐛bug

#39 fix: 자동 배포 오류 수정
  .github/workflows/dev_deploy.yml
  .gitignore
  Dockerfile
  gradlew
Labels: 🌏deploy, 🚨hotfix

#43 chore: CorsConfig 설정
  src/main/java/com/susanghan_guys/server/global/config/CorsConfig.java
Labels: ✨feature, ⚙️setting

#46 feat: 사용자 정보 조회 API
  src/main/java/com/susanghan_guys/server/global/common/code/ErrorCode.java
  src/main/java/com/susanghan_guys/server/global/common/code/SuccessCode.java
  src/main/java/com/susanghan_guys/server/global/config/SecurityConfig.java
  src/main/java/com/susanghan_guys/server/global/oauth2/application/CustomOAuth2UserService.java
  src/main/java/com/susanghan_guys/server/global/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/susanghan_guys/server/global/util/RedisUtil.java
  src/main/java/com/susanghan_guys/server/user/application/UserAuthService.java
  src/main/java/com/susanghan_guys/server/user/application/UserService.java
  src/main/java/com/susanghan_guys/server/user/domain/User.java
  src/main/java/com/susanghan_guys/server/user/dto/response/ExchangeTokenResponse.java
  src/main/java/com/susanghan_guys/server/user/presentation/UserAuthController.java
  src/main/java/com/susanghan_guys/server/user/presentation/swagger/UserAuthSwagger.java
  src/main/java/com/susanghan_guys/server/user/validator/UserValidator.java
Labels: ✨feature

#52 fix: cors 에러 해결
  src/main/java/com/susanghan_guys/server/global/config/CorsConfig.java
Labels: 🐛bug, 🚨hotfix

#53 feat: 마이페이지 관련 API
  src/main/java/com/susanghan_guys/server/global/common/code/ErrorCode.java
  src/main/java/com/susanghan_guys/server/global/common/code/SuccessCode.java
  src/main/java/com/susanghan_guys/server/global/config/SecurityConfig.java
  src/main/java/com/susanghan_guys/server/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/susanghan_guys/server/global/jwt/JwtProvider.java
  src/main/java/com/susanghan_guys/server/global/security/CurrentUserProvider.java
  src/main/java/com/susanghan_guys/server/global/security/CustomUserDetailService.java
  src/main/java/com/susanghan_guys/server/oauth2/application/CustomOAuth2UserService.java
  src/main/java/com/susanghan_guys/server/oauth2/application/TokenBlackListService.java
  src/main/java/com/susanghan_guys/server/oauth2/domain/OAuth2UserInfo.java
  src/main/java/com/susanghan_guys/server/oauth2/domain/RefreshToken.java
  src/main/java/com/susanghan_guys/server/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/susanghan_guys/server/oauth2/infrastructure/persistence/RefreshTokenRepository.java
  src/main/java/com/susanghan_guys/server/oauth2/infrastructure/userinfo/GoogleUserInfo.java
  src/main/java/com/susanghan_guys/server/oauth2/infrastructure/userinfo/KakaoUserInfo.java
  src/main/java/com/susanghan_guys/server/oauth2/infrastructure/userinfo/NaverUserInfo.java
  src/main/java/com/susanghan_guys/server/user/application/UserAuthService.java
  src/main/java/com/susanghan_guys/server/user/application/UserService.java
  src/main/java/com/susanghan_guys/server/user/domain/User.java
  src/main/java/com/susanghan_guys/server/user/dto/request/MyPageInfoRequest.java
  src/main/java/com/susanghan_guys/server/user/dto/response/MyPageInfoResponse.java
  src/main/java/com/susanghan_guys/server/user/exception/UserException.java
  src/main/java/com/susanghan_guys/server/user/exception/code/UserAuthErrorCode.java
  src/main/java/com/susanghan_guys/server/user/exception/code/UserErrorCode.java
  src/main/java/com/susanghan_guys/server/user/infrastructure/mapper/UserMapper.java
  src/main/java/com/susanghan_guys/server/user/presentation/UserController.java
  src/main/java/com/susanghan_guys/server/user/presentation/swagger/UserSwagger.java
  src/main/java/com/susanghan_guys/server/user/validator/UserValidator.java
Labels: ✨feature

#55 feat: 사용자 탈퇴 API
  src/main/java/com/susanghan_guys/server/global/common/CommonResponse.java
  src/main/java/com/susanghan_guys/server/global/common/code/BaseCode.java
  src/main/java/com/susanghan_guys/server/global/common/code/SuccessCode.java
  src/main/java/com/susanghan_guys/server/global/exception/BusinessException.java
  src/main/java/com/susanghan_guys/server/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/susanghan_guys/server/global/jwt/JwtProvider.java
  src/main/java/com/susanghan_guys/server/global/security/CustomUserDetails.java
  src/main/java/com/susanghan_guys/server/oauth2/application/CustomOAuth2UserService.java
  src/main/java/com/susanghan_guys/server/oauth2/domain/OAuth2UserInfo.java
  src/main/java/com/susanghan_guys/server/user/application/UserAuthService.java
  src/main/java/com/susanghan_guys/server/user/application/UserService.java
  src/main/java/com/susanghan_guys/server/user/domain/User.java
  src/main/java/com/susanghan_guys/server/user/domain/type/WithdrawalReason.java
  src/main/java/com/susanghan_guys/server/user/dto/request/UserWithdrawalRequest.java
  src/main/java/com/susanghan_guys/server/user/exception/UserAuthException.java
  src/main/java/com/susanghan_guys/server/user/exception/UserException.java
  src/main/java/com/susanghan_guys/server/user/exception/code/UserErrorCode.java
  src/main/java/com/susanghan_guys/server/user/infrastructure/persistence/UserRepository.java
  src/main/java/com/susanghan_guys/server/user/presentation/UserController.java
  src/main/java/com/susanghan_guys/server/user/presentation/swagger/UserAuthSwagger.java
  src/main/java/com/susanghan_guys/server/user/presentation/swagger/UserSwagger.java
  src/main/java/com/susanghan_guys/server/user/validator/UserValidator.java
Labels: ✨feature

#57 feat: DCA/YCC 작품 제출 기능 구현
  build.gradle
  src/main/java/com/susanghan_guys/server/contest/infrastructure/persistence/ContestRepository.java
  src/main/java/com/susanghan_guys/server/global/common/code/SuccessCode.java
  src/main/java/com/susanghan_guys/server/global/config/S3Config.java
  src/main/java/com/susanghan_guys/server/global/s3/application/S3Service.java
  src/main/java/com/susanghan_guys/server/user/infrastructure/persistence/UserRepository.java
  src/main/java/com/susanghan_guys/server/work/application/DcaWorkService.java
  src/main/java/com/susanghan_guys/server/work/application/YccWorkService.java
  src/main/java/com/susanghan_guys/server/work/application/support/WorkHelper.java
  src/main/java/com/susanghan_guys/server/work/domain/AdditionalFile.java
  src/main/java/com/susanghan_guys/server/work/domain/Member.java
  src/main/java/com/susanghan_guys/server/work/domain/Work.java
  src/main/java/com/susanghan_guys/server/work/domain/WorkMember.java
  src/main/java/com/susanghan_guys/server/work/domain/type/FilesType.java
  src/main/java/com/susanghan_guys/server/work/dto/DcaWorkSubmissionRequest.java
  src/main/java/com/susanghan_guys/server/work/dto/TeamMemberDto.java
  src/main/java/com/susanghan_guys/server/work/dto/YccWorkSubmissionRequest.java
  src/main/java/com/susanghan_guys/server/work/exception/WorkException.java
  src/main/java/com/susanghan_guys/server/work/exception/code/WorkErrorCode.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/mapper/DcaWorkMapper.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/mapper/YccWorkMapper.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/persistence/AdditionalFileRepository.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/persistence/MemberRepository.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/persistence/WorkMemberRepository.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/persistence/WorkRepository.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/saver/WorkSaver.java
  src/main/java/com/susanghan_guys/server/work/presentation/WorkController.java
  src/main/java/com/susanghan_guys/server/work/presentation/swagger/WorkSwagger.java
  src/main/java/com/susanghan_guys/server/work/validator/DcaWorkValidator.java
  src/main/java/com/susanghan_guys/server/work/validator/YccWorkValidator.java
Labels: ✨feature

#60 refactor: 신청하기 api 예외 처리 방식 변경
  src/main/java/com/susanghan_guys/server/work/application/DcaWorkService.java
  src/main/java/com/susanghan_guys/server/work/domain/AdditionalFile.java
  src/main/java/com/susanghan_guys/server/work/domain/TeamMember.java
  src/main/java/com/susanghan_guys/server/work/domain/WorkMember.java
  src/main/java/com/susanghan_guys/server/work/dto/DcaWorkSubmissionRequest.java
  src/main/java/com/susanghan_guys/server/work/dto/TeamMemberResponse.java
  src/main/java/com/susanghan_guys/server/work/dto/YccWorkSubmissionRequest.java
  src/main/java/com/susanghan_guys/server/work/exception/WorkException.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/persistence/TeamMemberRepository.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/saver/WorkSaver.java
  src/main/java/com/susanghan_guys/server/work/presentation/WorkController.java
  src/main/java/com/susanghan_guys/server/work/presentation/swagger/WorkSwagger.java
Labels: ♻️refactor

#66 fix: DCA 작품 Brand 한글 허용
  src/main/java/com/susanghan_guys/server/work/application/DcaWorkService.java
  src/main/java/com/susanghan_guys/server/work/domain/type/Brand.java
  src/main/java/com/susanghan_guys/server/work/dto/DcaWorkSubmissionRequest.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/mapper/DcaWorkMapper.java
  src/main/java/com/susanghan_guys/server/work/validator/DcaWorkValidator.java
Labels: 🐛bug, 🚨hotfix

#69 fix: DCA Category 소문자 허용
  src/main/java/com/susanghan_guys/server/work/domain/type/Category.java
Labels: 🐛bug, 🚨hotfix

#73 fix: 토큰 만료 후, 302 에러
  src/main/java/com/susanghan_guys/server/global/config/SecurityConfig.java
  src/main/java/com/susanghan_guys/server/global/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/susanghan_guys/server/global/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/susanghan_guys/server/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/susanghan_guys/server/global/security/jwt/JwtProperties.java
  src/main/java/com/susanghan_guys/server/global/security/jwt/JwtProvider.java
  src/main/java/com/susanghan_guys/server/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/susanghan_guys/server/user/application/UserAuthService.java
  src/main/java/com/susanghan_guys/server/user/presentation/UserAuthController.java
Labels: 🐛bug, 🚨hotfix

#75 feat: 내 리포트 조회 API
  src/main/java/com/susanghan_guys/server/global/common/code/SuccessCode.java
  src/main/java/com/susanghan_guys/server/user/application/UserService.java
  src/main/java/com/susanghan_guys/server/user/domain/User.java
  src/main/java/com/susanghan_guys/server/work/application/DcaWorkService.java
  src/main/java/com/susanghan_guys/server/work/application/ReportService.java
  src/main/java/com/susanghan_guys/server/work/application/YccWorkService.java
  src/main/java/com/susanghan_guys/server/work/application/validator/DcaWorkValidator.java
  src/main/java/com/susanghan_guys/server/work/application/validator/YccWorkValidator.java
  src/main/java/com/susanghan_guys/server/work/domain/Work.java
  src/main/java/com/susanghan_guys/server/work/domain/type/ReportStatus.java
  src/main/java/com/susanghan_guys/server/work/dto/request/DcaWorkSubmissionRequest.java
  src/main/java/com/susanghan_guys/server/work/dto/request/YccWorkSubmissionRequest.java
  src/main/java/com/susanghan_guys/server/work/dto/response/MyReportListResponse.java
  src/main/java/com/susanghan_guys/server/work/dto/response/MyReportResponse.java
  src/main/java/com/susanghan_guys/server/work/dto/response/TeamMemberResponse.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/mapper/DcaWorkMapper.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/mapper/YccWorkMapper.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/persistence/WorkRepository.java
  src/main/java/com/susanghan_guys/server/work/infrastructure/saver/WorkSaver.java
  src/main/java/com/susanghan_guys/server/work/presentation/ReportController.java
  src/main/java/com/susanghan_guys/server/work/presentation/WorkController.java
  src/main/java/com/susanghan_guys/server/work/presentation/swagger/ReportSwagger.java
  src/main/java/com/susanghan_guys/server/work/presentation/swagger/WorkSwagger.java
Labels: ✨feature
